feat(observability): consume COSI credentials for loki storage

diff --git a/infrastructure/observability-core/loki/statefulset-default-loki.yaml b/infrastructure/observability-core/loki/statefulset-default-loki.yaml
--- a/infrastructure/observability-core/loki/statefulset-default-loki.yaml
+++ b/infrastructure/observability-core/loki/statefulset-default-loki.yaml
@@ -29,21 +29,9 @@ spec:
       automountServiceAccountToken: true
       containers:
       - args:
-        - -config.file=/etc/loki/loki.yaml
+        - -config.file=/etc/loki-runtime/loki.yaml
         - -target=all
-        env:
-        - name: AWS_ACCESS_KEY_ID
-          valueFrom:
-            secretKeyRef:
-              key: MINIO_ACCESS_KEY
-              name: loki-s3
-              optional: false
-        - name: AWS_SECRET_ACCESS_KEY
-          valueFrom:
-            secretKeyRef:
-              key: MINIO_SECRET_KEY
-              name: loki-s3
-              optional: false
+        env: []
         image: grafana/loki
         imagePullPolicy: IfNotPresent
         livenessProbe:
@@ -91,16 +79,62 @@ spec:
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         volumeMounts:
-        - mountPath: /etc/loki/loki.yaml
+        - mountPath: /etc/loki-runtime
           mountPropagation: None
-          name: config
+          name: loki-runtime
           readOnly: true
-          subPath: loki.yaml
         - mountPath: /loki
           mountPropagation: None
           name: data
       dnsPolicy: ClusterFirst
       enableServiceLinks: true
+      initContainers:
+      - args:
+        - |
+          bucket_info=/cosi/loki/BucketInfo
+          template=/etc/loki-template/loki.yaml
+          config=/etc/loki-runtime/loki.yaml
+
+          parse() {
+            sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$bucket_info"
+          }
+
+          bucket=$(parse bucketName)
+          endpoint=$(parse endpoint)
+          region=$(parse region)
+          access_key=$(parse accessKeyID)
+          secret_key=$(parse accessSecretKey)
+
+          if [ "$bucket" != "loki" ] || [ -z "$endpoint" ] || [ -z "$region" ] || [ -z "$access_key" ] || [ -z "$secret_key" ]; then
+            echo "ERROR: COSI BucketInfo is missing required Loki S3 fields"
+            exit 1
+          fi
+
+          endpoint=${endpoint#http://}
+          endpoint=${endpoint#https://}
+
+          sed \
+            -e "s|__LOKI_ACCESS_KEY_ID__|$access_key|g" \
+            -e "s|__LOKI_BUCKET__|$bucket|g" \
+            -e "s|__LOKI_ENDPOINT__|$endpoint|g" \
+            -e "s|__LOKI_REGION__|$region|g" \
+            -e "s|__LOKI_SECRET_ACCESS_KEY__|$secret_key|g" \
+            "$template" > "$config"
+        command:
+        - /bin/sh
+        - -ec
+        image: busybox:1.36
+        imagePullPolicy: IfNotPresent
+        name: render-loki-config
+        volumeMounts:
+        - mountPath: /cosi/loki
+          name: loki-cosi
+          readOnly: true
+        - mountPath: /etc/loki-template
+          name: config
+          readOnly: true
+        - mountPath: /etc/loki-runtime
+          name: loki-runtime
       nodeSelector:
         kubernetes.io/hostname: hestia
       restartPolicy: Always
@@ -114,6 +148,11 @@ spec:
           name: loki-config
           optional: false
         name: config
+      - emptyDir: {}
+        name: loki-runtime
+      - name: loki-cosi
+        secret:
+          secretName: loki-cosi-s3
   updateStrategy:
     type: RollingUpdate
   volumeClaimTemplates:
